export const ROUTE_NAMES = {
  MAIN: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  ORIGINAL_SPARE_PARTS: '/original-spare-parts',
  ORIGINAL_SPARE_PARTS_VEHICLES: '/original-spare-parts/vehicles',
  ORIGINAL_SPARE_PARTS_CATEGORIES: '/original-spare-parts/categories',
  CAR_BODY_SPARE_PARTS: '/car-body-spare-parts',
  CAR_OILS: '/car-oils',
  ACCUMULATORS: '/accumulators',
  NON_ORIGINAL_SPARE_PARTS: '/non-original-spare-parts',
  MAINTENANCE_SPARE_PARTS: '/maintenance-spare-parts',
  CAR_CHEMISTRY: '/car-chemistry',
  CAR_LAMPS: '/car-lamps',
  VAZ_GAZ_KAMAZ_SPARE_PARTS: '/vaz-gaz-kamaz-spare-parts',
  AUTO_GLASSES: '/auto-glasses',
  WHEELS: '/wheels',
  SHOPPING_CART: '/basket',
  FORGOT_PASSWORD: '/forgot-password',
  SUPPLIER_SIGN_UP: '/sign-up-supplier',
  SUPPORT: '/support',

  CUSTOMER: '/customer',
  CUSTOMER_PERSONAL_INFO: '/customer/personal-info',
  CUSTOMER_ORDERS: '/customer/orders',
  CUSTOMER_ADDRESSES: '/customer/addresses',
  CUSSTOMER_REQUISITES: '/customer/requisites',
  CUSTOMER_CHATS: '/customer/chats',

  SUPPLIER: '/supplier',
  SUPPLIER_CATALOG: '/supplier/catalog',
  SUPPLIER_PRICE_LISTS: '/supplier/price-lists',
  SUPPLIER_ORDERS: '/supplier/orders',
  SUPPLIER_STORES: '/supplier/stores',
  SUPPLIER_REQUISITES: '/supplier/requisites',
  SUPPLIER_RECEIPTS: '/supplier/receipts',
  SUPPLIER_CHATS: '/supplier/chats',
  SUPPLIER_ACCOUNTING: '/supplier/accounting',

  MANAGER: '/manager',
  MANAGER_SUPPLIERS: '/manager/suppliers',
  MANAGER_CUSTOMERS: '/manager/customers',
  MANAGER_ORDERS: '/manager/orders',
  MANAGER_STORES: '/manager/stores'
} as const
